# setting up solidqueue to use a separate db as it is preferred in the docs
# additionally configuring local dev to work this way as well, even though
# it technically isn't needed. aiming to test mission control etc.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# cache: &cache
#   <<: *default
#   migrations_paths: db/cache_migrate
queue: &queue
  <<: *default
  migrations_paths: db/queue_migrate

development:
  primary:
    <<: *default
    database: ninetynine_staples_mono_development
  # cache:
  #   <<: *cache
  #   database: myapp_development_cache
  queue:
    <<: *queue
    database: ninetynine_dev_queue

test:
  <<: *default
  database: ninetynine_staples_mono_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  # cache:
  #   <<: *cache
  #   url: <%= ENV['DATABASE_URL']&.+('_cache') %>
  queue:
    <<: *queue
    url: <%= ENV['DATABASE_QUEUE_URL'] %>
